# Pytorch Basic
---

## What is Pytorch?

> PyTorch is a deep learning framework for fast, flexible experimentation.

* Articles that you can read:
    - https://awni.github.io/pytorch-tensorflow/
    - https://deepsense.ai/keras-or-pytorch/
    
I think there are many pytorch basic tutorials that you can follow. Let me introduce you some links in References, first.

## Reference

* pytorch documentation: https://pytorch.org/docs/stable/index.html
* pytorch tutorial documentaion: https://pytorch.org/tutorials/index.html
* pytorch nlp tutorial documentaion: https://pytorch.org/tutorials/beginner/deep_learning_nlp_tutorial.html
* PytorchZeroAll: https://github.com/hunkim/PyTorchZeroToAll
* yunjey's pytorch tutorial: https://github.com/yunjey/pytorch-tutorial

## Tensor

What is tensor? In mathematics, a tensor is an arbitrarily complex geometric object that maps in a (multi-)linear manner geometric vectors, scalars, and other tensors to a resulting tensor. 

If you don't familiar with math, first you can think tensor as a container. 

![](./figs/2_tensor.png)

In Morden PyTorch, It is similar to numpy array.

### Create a Tensor

In [1]:
import numpy as np
import torch
print(f" torch: {torch.__version__} \n numpy: {np.__version__}")

 torch: 1.0.0 
 numpy: 1.15.4


`torch.Tensor` basically create tensor in float type tensor `torch.FloatTensor`, you can also create long type tensor by `torch.LongTensor`.

In [2]:
# create 2x3 matrix tensor from list / numpy array
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
y = torch.LongTensor(np.array([[1, 2, 3], [4, 5, 6]]))
print(x)
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
# back to list / numpy array
print(f"tensor --> list: \n{x.tolist()}")
print(f"tensor --> numpy: \n{y.numpy()}")

tensor --> list: 
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
tensor --> numpy: 
[[1 2 3]
 [4 5 6]]


random init a tensor

In [4]:
# generate 3 x 3 x 3 tensor
torch.rand(3, 3, 3)

tensor([[[0.1344, 0.0791, 0.0694],
         [0.5245, 0.3921, 0.7457],
         [0.1981, 0.8041, 0.4248]],

        [[0.9910, 0.3388, 0.2575],
         [0.9973, 0.9845, 0.9083],
         [0.5435, 0.1598, 0.2372]],

        [[0.4444, 0.0942, 0.4111],
         [0.2681, 0.7454, 0.7190],
         [0.3033, 0.5510, 0.4298]]])

### Tensor Manipulation

In [8]:
x = torch.rand(3, 3, 3)
print(x)

tensor([[[0.5455, 0.1457, 0.8374],
         [0.6280, 0.4433, 0.0678],
         [0.1391, 0.6799, 0.2357]],

        [[0.1622, 0.0284, 0.2170],
         [0.4316, 0.7175, 0.1293],
         [0.5199, 0.6196, 0.4644]],

        [[0.9656, 0.4092, 0.0643],
         [0.1688, 0.1702, 0.0420],
         [0.4616, 0.9186, 0.3965]]])


get size of tensor

In [9]:
print(x.size())
print(x.shape)

torch.Size([3, 3, 3])
torch.Size([3, 3, 3])


slicing: get 3rd dimension, 1st row, 2nd column of x

In [20]:
print(x[2, 0, 1])

tensor(0.4092)


### Frequently used opteration

add, sum, mean