# Pytorch Basic
---

## What is Pytorch?

> PyTorch is a deep learning framework for fast, flexible experimentation.

* Articles that you can read:
    - https://awni.github.io/pytorch-tensorflow/
    - https://deepsense.ai/keras-or-pytorch/
    
I think there are many pytorch basic tutorials that you can follow. Let me introduce you some links in References, first.

## Reference

* pytorch documentation: https://pytorch.org/docs/stable/index.html
* pytorch tutorial documentaion: https://pytorch.org/tutorials/index.html
* pytorch nlp tutorial documentaion: https://pytorch.org/tutorials/beginner/deep_learning_nlp_tutorial.html
* PytorchZeroAll: https://github.com/hunkim/PyTorchZeroToAll
* yunjey's pytorch tutorial: https://github.com/yunjey/pytorch-tutorial

## Tensor

What is tensor? In mathematics, a tensor is an arbitrarily complex geometric object that maps in a (multi-)linear manner geometric vectors, scalars, and other tensors to a resulting tensor. 

In PyTorch, It is similar to numpy array.

### Create a Tensor

In [5]:
import numpy as np
import torch
print(f" torch: {torch.__version__} \n numpy: {np.__version__}")

 torch: 1.0.0 
 numpy: 1.15.4


`torch.Tensor` basically create tensor in float type tensor `torch.FloatTensor`, you can also create long type tensor by `torch.LongTensor`.

In [11]:
# create 2x3 matrix tensor from list / numpy array
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
y = torch.LongTensor(np.array([[1, 2, 3], [4, 5, 6]]))
print(x)
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
# back to list / numpy array
print(f"tensor --> list: \n{x.tolist()}")
print(f"tensor --> numpy: \n{y.numpy()}")

tensor --> list: 
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
tensor --> numpy: 
[[1 2 3]
 [4 5 6]]


random init a tensor

In [19]:
# generate 3 x 3 x 3 tensor
torch.rand(3, 3, 3)

tensor([[[0.8717, 0.8696, 0.9691],
         [0.8374, 0.5689, 0.1465],
         [0.7704, 0.0565, 0.8802]],

        [[0.5110, 0.5724, 0.1466],
         [0.5107, 0.6360, 0.9014],
         [0.1925, 0.3146, 0.0357]],

        [[0.0727, 0.8939, 0.3352],
         [0.6004, 0.7361, 0.6149],
         [0.8432, 0.9225, 0.7574]]])

### Tensor Manipulation

In [18]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


get size of tensor

In [17]:
x.size()

torch.Size([2, 3])

slicing: get 1st row, 2nd column of x

In [20]:
x[0, 1]

tensor(2.)

### Tensor 