Pytorch Basic
===

## What is PyTorch?

> PyTorch is a deep learning framework for fast, flexible experimentation.

* Articles that you can read:
    - https://awni.github.io/pytorch-tensorflow/
    - https://deepsense.ai/keras-or-pytorch/
    
I think there are many pytorch basic tutorials that you can follow. Let me introduce you some links in References, first.

## Reference

* pytorch documentation: https://pytorch.org/docs/stable/index.html
* pytorch tutorial documentaion: https://pytorch.org/tutorials/index.html
* pytorch nlp tutorial documentaion: https://pytorch.org/tutorials/beginner/deep_learning_nlp_tutorial.html
* PytorchZeroAll: https://github.com/hunkim/PyTorchZeroToAll
* yunjey's pytorch tutorial: https://github.com/yunjey/pytorch-tutorial

---

## Tensor

What is tensor? In mathematics, a tensor is an arbitrarily complex geometric object that maps in a (multi-)linear manner geometric vectors, scalars, and other tensors to a resulting tensor. 

https://youtu.be/rlpziTbJZk0

real definition of tensor

https://www.youtube.com/watch?v=TvxmkZmBa-k

But in deep learning, a little bit different , first you can think tensor as a container that contatins numbers

![](./figs/2_tensor.png)

In Morden PyTorch, It is similar to numpy array.

### Create a Tensor

* how to create a tensor
* types of tensor

#### how to create a tensor

In [1]:
import numpy as np
import torch
print(f" torch: {torch.__version__} \n numpy: {np.__version__}")

 torch: 1.0.0 
 numpy: 1.15.4


you can create tensors from lists or numpy array. or vice versa

In [2]:
# create 2x3 matrix tensor from list / numpy array
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])
b = torch.Tensor(np.array([[9, 6, 1], [5, 3, 2]]))
print(a)
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[9., 6., 1.],
        [5., 3., 2.]])


In [3]:
# back to list / numpy array
print(f"tensor --> list: \n{a.tolist()}")
print(f"tensor --> numpy: \n{b.numpy()}")

tensor --> list: 
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
tensor --> numpy: 
[[9. 6. 1.]
 [5. 3. 2.]]


random init a tensor / zeros / ones

In [4]:
# generate 2 x 2 x 3 tensor
a = torch.rand(2, 2, 3)
print(a)

tensor([[[0.5588, 0.5245, 0.9022],
         [0.9615, 0.2320, 0.2519]],

        [[0.2189, 0.1801, 0.5956],
         [0.7085, 0.4415, 0.9118]]])


In [5]:
# if you want to create a tensor like x you can do it by 2 ways
b = torch.zeros(2, 2, 3)
c = torch.zeros_like(a)
print(b)
print("-"*30)
print(c)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
------------------------------
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
d = torch.ones_like(a)
print(d)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


#### Type of Tensor

`torch.Tensor` basically create tensor in float type tensor `torch.FloatTensor`, you can also create long type tensor by `torch.LongTensor`.

In [7]:
a = np.array([[9, 6, 1], [5, 3, 2]])
b = torch.Tensor(a)
c = torch.FloatTensor(a)
d = torch.LongTensor(a)
print(f" b: {b.type()}\n c: {c.type()}\n d: {d.type()}")

 b: torch.FloatTensor
 c: torch.FloatTensor
 d: torch.LongTensor


`torch.ByteTensor` normally is used for a boolean types. If you use `torch.Tensor` for booleans, it will automatically change it to 1(True) or 0(False) float type tensor

In [8]:
e = [True, False, False, True]
f = torch.Tensor(e)
g = torch.ByteTensor(e)
print(f)
print(g)
print("-"*30)
print(f" f: {f.type()}\n g: {g.type()}")

tensor([1., 0., 0., 1.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
------------------------------
 f: torch.FloatTensor
 g: torch.ByteTensor


It is also easy to change types

In [9]:
print(f"change torch.FloatTensor to torch.LongTensor is 'c.long()' for instance")
print(c.long()) # if you want to change it eternally, don't forget to assign it to your computer memory

change torch.FloatTensor to torch.LongTensor is 'c.long()' for instance
tensor([[9, 6, 1],
        [5, 3, 2]])


In [10]:
print(f"change torch.FloatTensor to torch.ByteTensor is 'f.byte()' for instance")
print(f.byte()) # if you want to change it eternally, don't forget to assign it to your computer memory

change torch.FloatTensor to torch.ByteTensor is 'f.byte()' for instance
tensor([1, 0, 0, 1], dtype=torch.uint8)


### Tensor Manipulation

* dim / size / shape 
* slicing / item
* view(equal as reshape in numpy) / concat / stack / squeeze / unsqueeze
* add(2types + inplace opteration) / multiplication: mul, dot, @, mm
* sum / mean / max & argmax

for more maths operation plz visit: [https://pytorch.org/docs/stable/torch.html#math-operations](https://pytorch.org/docs/stable/torch.html#math-operations)

In [11]:
torch.manual_seed(777)
x = torch.randint(0, 10, size=(2, 3, 4))
print(x)

tensor([[[5, 9, 1, 8],
         [5, 7, 7, 7],
         [3, 4, 1, 7]],

        [[2, 0, 6, 3],
         [2, 3, 0, 0],
         [9, 5, 4, 2]]])


this 3-dimensional tensor is looks like

![](figs/2_tensorex.png)

#### ndim / size / shape

if you want to know what kind of a container (what size of a tensor) is, you can use `size` method or `shape` attribute

In [29]:
# what dimension?
print(x.dim())
# what size/shape?
print(x.size())
print(x.shape)

3
torch.Size([2, 3, 4])
torch.Size([2, 3, 4])


#### slicing / item

like numpy array, it's easy to select 1st dimension, 3rd row and 2nd column element of data x

In [1]:
print(x[0, 2, 1])

NameError: name 'x' is not defined

`index_select` returns a new tensor which indexes the input tensor along dimension `dim` using the entries in `index` which is a `torch.LongTensor`.

In [14]:
x.size()

torch.Size([2, 3, 4])

In [15]:
index_1 = torch.LongTensor([1])
index_2 = torch.LongTensor([0, 2])
index_3 = torch.LongTensor([1, 2, 3])
# select 
for i, index in enumerate([index_1, index_2, index_3]):
    print(f"select dim={i}, indices={index.numpy()}")
    print(x.index_select(i, index), "\n")

select dim=0, indices=[1]
tensor([[[2, 0, 6, 3],
         [2, 3, 0, 0],
         [9, 5, 4, 2]]]) 

select dim=1, indices=[0 2]
tensor([[[5, 9, 1, 8],
         [3, 4, 1, 7]],

        [[2, 0, 6, 3],
         [9, 5, 4, 2]]]) 

select dim=2, indices=[1 2 3]
tensor([[[9, 1, 8],
         [7, 7, 7],
         [4, 1, 7]],

        [[0, 6, 3],
         [3, 0, 0],
         [5, 4, 2]]]) 



`masked_select` is also useful to select datas. if you want to select numbers are greater than 5, do following

In [16]:
mask = x.ge(5)  # ge: greater or equal, returns torch.ByteTensor
x.masked_select(mask)

tensor([5, 9, 8, 5, 7, 7, 7, 7, 6, 9, 5])

In [17]:
# if you want to keep shape of tensor x, just mutiplicate it.
x * mask.type_as(x)

tensor([[[5, 9, 0, 8],
         [5, 7, 7, 7],
         [0, 0, 0, 7]],

        [[0, 0, 6, 0],
         [0, 0, 0, 0],
         [9, 5, 0, 0]]])

if you have one element tensor(scalar) can use `item()` method to bring it out 

In [18]:
print(torch.FloatTensor([5.3451]).item())

5.345099925994873


#### view / concat / stack / squeeze / unsqueeze

`view` method is equal to `reshape` in numpy. The returned tensor shares the same data and must have the same number of elements, but may have a different size. 

In [19]:
x

tensor([[[5, 9, 1, 8],
         [5, 7, 7, 7],
         [3, 4, 1, 7]],

        [[2, 0, 6, 3],
         [2, 3, 0, 0],
         [9, 5, 4, 2]]])

In [113]:
print(f"change '{x.size()}' to '{x.view(2, 2, 6).size()}'")
print(x.view(2, 2, 6))

change 'torch.Size([2, 3, 4])' to 'torch.Size([2, 2, 6])'
tensor([[[5, 9, 1, 8, 5, 7],
         [7, 7, 3, 4, 1, 7]],

        [[2, 0, 6, 3, 2, 3],
         [0, 0, 9, 5, 4, 2]]])


* https://stackoverflow.com/questions/32034237/how-does-numpys-transpose-method-permute-the-axes-of-an-array?fbclid=IwAR0RmfglnUPFGt6x4fvTDXAccOSsHYxfkcuuAzVSgfBcgQAX6VzgXxvr8sc

`concat` is 

### Frequently used opteration

add, sum, mean